### ISSUE TITLE
no way to use lambda as a comparator for tbb_concurrent_priority_queue 

### ISSUE THREAD

**Issue by anton-potapov** [intel/tbb#109]
this code does not compile : 
```cpp
struct tile_node {
    size_t index = 0;
};

auto comparator = [](tile_node const * lhs, tile_node const * rhs){
       return lhs->index < rhs->index;
 };

tbb::concurrent_priority_queue<tile_node* , decltype(comparator)>   q; 
```

where intel C++ compiler issues an error: 
<pre>
include/tbb/concurrent_priority_queue.h(89): error: the default constructor of "lambda [](const tile_node *, const tile_node *)->bool" cannot be referenced -- it is a deleted function
<pre>

**Comment by tbbdev** [comment]
Fixed in [TBB 2019 Update 5](https://github.com/01org/tbb/tree/2019_U5).
