### ISSUE TITLE
[Feature Request] Add support for enqueuing tbb::task into tbb::task_arena

### ISSUE THREAD

**Issue by emptyVoid** [intel/tbb#116]
Currently ```tbb::task_arena::enqueue``` supports "functors" only, and the only viable method for passing ```tbb::task```s into arena I see is something like this:
```c++
arena.enqueue( [task] () { tbb::task::spawn( *task ); } );
```

Would be really great to have some "native" support for ```tbb::task``` enqueuing in the ```tbb::task_arena```.

**Comment by anton-potapov** [comment]
+1

**Comment by tbbdev** [comment]
Implemented in [TBB 2019 U6](https://github.com/intel/tbb/blob/2019_U6/CHANGES).

**Comment by emptyVoid** [comment]
Great, thanks!

Though since I'm unable to try it out any time soon I've got a question: does the implementation allow enqueuing from a thread with no task scheduler initialized?

I'm asking because the implementation looks quite similar to a hack I employed before, here's a snippet:
```c++
class task_arena_extensions
{
public:
    static void enqueue( tbb::task_arena& arena, tbb::task& task )
    {
        auto& friendlyArena = (friendly_task_arena&)arena;
        friendlyArena.initialize();
        friendlyArena.internal_enqueue( task, 0 );
    }

private:
    class friendly_task_arena : tbb::task_arena { friend class task_arena_extensions; };
};
```
And I had to replace it with ```arena.enqueue( [task] () { tbb::task::spawn( *task ); } );``` since the hack didn't work for threads with no active task scheduler (due to either a crash in release or an assertion failure in debug, iirc [here](https://github.com/intel/tbb/blob/2019_U6/src/tbb/arena.cpp#L579)).

**Comment by akukanov** [comment]
As of now, the implementation indeed requires the calling thread to have an active task scheduler. We will improve that in a following update. Thanks for your feedback!

**Comment by tbbdev** [comment]
Improved in [TBB 2019 U8](https://github.com/intel/tbb/blob/2019_U8/CHANGES).

**Comment by emptyVoid** [comment]
Great, thank you!
