### ISSUE TITLE
[CMake] TBBConfig.cmake can't find the libraries

### ISSUE THREAD

**Issue by ldionne** [intel/tbb#135]
Hi,

`TBBConfig.cmake` currently says:

```cmake
# ...

get_filename_component(_tbb_root "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_tbb_root "${_tbb_root}" PATH)

# ...

get_filename_component(_tbb_lib_path "${_tbb_root}/lib/${_tbb_arch_subdir}/${_tbb_compiler_subdir}" ABSOLUTE)
```

However, this file is normally installed in:

```
<prefix>/lib/cmake/TBB/TBBConfig.cmake
```

As a result, `${CMAKE_CURRENT_LIST_FILE}` is `<prefix>/lib/cmake/TBB/TBBConfig.cmake`, and `_tbb_root` is `<prefix>/lib/cmake`. We then try to look for the libraries in `${_tbb_root}/lib/<arch>/<compiler>`, which is `<prefix>/lib/cmake/lib/<arch>/<compiler>`. This is incorrect, as we should be looking into `<prefix>/lib/<arch>/<compiler>`. The problem is that `_tbb_root` currently points to the root of the CMake config files installation, as opposed to the prefix where TBB was installed. Instead, we should use:

```
get_filename_component(_tbb_root "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_tbb_root "${_tbb_root}" PATH)
get_filename_component(_tbb_root "${_tbb_root}" PATH)
get_filename_component(_tbb_root "${_tbb_root}" PATH)
```

**Comment by AlexVeprev** [comment]
Hi @ldionne,

Which `TBBConfig.cmake` do you mean?
If you mean `TBBConfig.cmake` from binary packages provided on the [release page](https://github.com/01org/tbb/releases), then yes, it will not work if you install it in the described way. But this `TBBConfig.cmake` is designed to be used inside the binary package where it is provided, please see an example in [README of Parallel STL sample gamma_correction](https://github.com/intel/parallelstl/tree/releases/examples/gamma_correction#download-tbb-and-build-the-example-using-cmake-linux).

For your case the [TBBInstallConfig module](https://github.com/01org/tbb/tree/tbb_2019/cmake#tbbinstallconfig) (developed in scope of PRs #119, #126, #127) may be suitable, you can generate a proper TBBConfig.cmake for your TBB installation.

**Comment by ldionne** [comment]
I am talking about the `TBBConfig.cmake` file as installed by Homebrew's `tbb` formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tbb.rb

**Comment by AlexVeprev** [comment]
@ldionne I created a PR to fix `tbb` formula in Homebrew: https://github.com/Homebrew/homebrew-core/pull/38844

**Comment by ldionne** [comment]
Thanks!

**Comment by AlexVeprev** [comment]
The TBB formula was updated in Homebrew. Now everything works well on my machine. @ldionne, could you please check it on your side and close the issue if everything is ok?

@hjmjohnson, this might be interesting for you too.

**Comment by ldionne** [comment]
Thanks, I confirmed it works as expected locally.
