### ISSUE TITLE
[CMake] Add CMake files into TBB packages in distributions

### ISSUE THREAD

**Issue by anton-malakhov** [intel/tbb#141]
TBB distributes binary archives with pre-compiled libraries along with CMake files.
Intel/your team also distributes [APT/DEB](https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-apt-repo), Nuget, Conda packages, e.g. https://anaconda.org/intel/tbb-devel/files, which don't have CMake files inside.
Please add cmake files so that applications using TBB could find TBB cmake package without any additional effort. Arrow needs it right now. Please align `build/build.py --install-devel` to include CMake files as well so that Conda-Forge and Anaconda distributions will remain aligned with Intel packages.

**Comment by tbbdev** [comment]
Done in [TBB 2017 U7](https://github.com/intel/tbb/blob/2019_U7/CHANGES).

**Comment by anton-malakhov** [comment]
Thank you!!!
