### ISSUE TITLE
traverse concurrent_hash_map 

### ISSUE THREAD

**Issue by x-x-p** [intel/tbb#144]
I have a question.
In multithreading, how do you traverse concurrent_hash_map while other threads are inserting and erasing?  don't use additional mutex?

**Comment by anton-malakhov** [comment]
Please check out this blog: https://software.intel.com/en-us/blogs/2010/05/14/traversing-concurrent_hash_map-concurrently
In short: `You cannot traverse concurrently with an erase() operation. Use a mutex around erase and traversal code if you still need both running in different threads.` or use `concurrent_unordered_map` instead.

**Comment by x-x-p** [comment]
thank you, but erasing is not safe in concurrent_unordered_map,  concurrent_unordered_map only has unsafe_erase(), how to do in diffenrent threads, in the next example.
`
thread 1:
for(auto& pair : concurrent_unordered_map)
{
      // only read
}

thread 2:
concurrent_unordered_map::insert()

thread 3:
concurrent_unordered_map::unsafe_erase()
`
what is the safest way to do it?

**Comment by anton-malakhov** [comment]
Use a mutex. cHmap has unsafe iterators, cUmap has unsafe erase. In absence of GC, there is no way of having both safe at the same time. You have to make a choice trying to minimize impact to the critical path of your application. As I said above, there are at least two ways to do it:
1. Mutex around `concurrent_hash_map::erase()` and around your traversal function. It allows you to maintain high concurrency by keeping mutex away from `find()` and `insert()` but the traversal guarantees are very weak as described in the blog.
2. Mutex around `concurrent_unordered_map::unsafe_erase()` and parallel region of accessing the table. It gives you strong guarantees of traversal and concurrent find/`insert()` but requires serial regions for performing erases. It might be acceptable if you have serial regions anyway and the number of erases are small and they can be deferred (e.g. by marking elements 'dead').

**Comment by x-x-p** [comment]
thks

**Comment by mjrao** [comment]
@x-x-p  How do you deal with this problem in the end？
