### ISSUE TITLE
TBB 2019U6 and GCC 9.1 fails with optimized IA32 build on Linux

### ISSUE THREAD

**Issue by ms178** [intel/tbb#145]
Hi,

even though GCC 9.1 is currently not officially supported and was just released, I just wanted to give you a heads up for the following issue which I've found while compiling TBB 2019 U6 from your sources with optimized CFLAGS for the IA32 target (by altering the release build in the Makefile to: -O3 -mtune=native -march=native -fuse-linker-plugin -flto -fno-semantic-interposition -falign-functions=32 -feliminate-unused-debug-types -ftree-loop-distribution -floop-nest-optimize -fgraphite-identity -floop-parallelize-all -ftree-parallelize-loops=4 -DUSE_PTHREAD). In addition, I also delete the -march=pentium4 flag in the IA32 target within the Makefile. The strange part is that the compilation successfully completes, but when opening the 32bit application where I use the TBB libraries, the applications starts up fine but crashes back to desktop while loading. All is fine when using the GCC 9.1 compiled debug builds, though. I've tried less aggressive compiler flags, but the same issue persists. Hence it could also be a compiler issue with optimizations enabled. 

All is fine when building as described above with GCC 8.3.1 (which is also not officially supported yet). I forogt to add that I am on openSUSE Tumbleweed. The GCC 9.1 build was from the repository of Martin Liska, home:marxin:home:marxin:gcc-periodic-testing-v2 (currently not available anymore).

**Comment by ms178** [comment]
Update: I've verified that the issue also exists with the default flags and newer builds of GCC from that repository. GCC version string is currently: gcc version 10.0.0 20190517 (experimental) (SUSE Linux)

**Comment by ms178** [comment]
As mentioned in the linked Thread, this seems to be a GCC issue and still in gcc version 10.0.0 20190524 (experimental). TBB 2019 U7 is also affected.

**Comment by ms178** [comment]
I did some experiments and I think to have narrowed down the cause quite a bit. Every Optimization level other than -O0 does lead to that error, even -Os. I've tested O1, O2, O3 and Os (all together solely with -mtune=native -march=native -DUSE_PTHREAD).

I can combine -O0 with quite a few other flags, though and get working binaries, e.g. this fancy setting produces working binaries: -O0 -mtune=native -march=native -fuse-linker-plugin -flto -fno-semantic-interposition -falign-functions=32 -feliminate-unused-debug-types -ftree-loop-distribution -floop-nest-optimize -fgraphite-identity -floop-parallelize-all -ftree-parallelize-loops=4 -DUSE_PTHREAD

**Comment by ms178** [comment]
Quick update: The issue still persits with TBB 2019 U8 and gcc version 10.0.0 20190612 (experimental) (SUSE Linux), I've also filed a bug with the GCC folks here: https://bugzilla.opensuse.org/show_bug.cgi?id=1136294

I'v uploaded a non-working and working Linux 32 bit build there (both using the -g flag for debugging) if you want to take a look yourself. The non-working build uses -O3 and the working -O0, the additional flags used don't make a difference in the outcome.

**Comment by alexey-katranov** [comment]
It does not seem that something needs to be fixed in TBB. Or do you expect that the issue will remain with the released version of gcc and changes in TBB are required?

**Comment by ms178** [comment]
I also assume that GCC is the offender here, as GCC 8.3.1 is fine. But as GCC 9.1 exposed undefined behaviour in other projects already, I thought you could help to identify the problem and the issue could be with GCC or on your end. Here are all the warnings which show up during the compilation process with gcc version 10.0.0 20190612 which might help to identify other issues:

In file included from ../../src/tbb/concurrent_hash_map.cpp:17:
../../include/tbb/concurrent_hash_map.h: In constructor ‘tbb::interface5::internal::hash_map_base::hash_map_base()’:
../../include/tbb/concurrent_hash_map.h:127:51: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘class tbb::interface5::internal::hash_map_base’ with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
  127 |                 + embedded_buckets*sizeof(bucket) ); // n*8 or n*16
      |                                                   ^
../../include/tbb/concurrent_hash_map.h:79:11: note: ‘class tbb::interface5::internal::hash_map_base’ declared here
   79 |     class hash_map_base {
      |           ^~~~~~~~~~~~~../../src/tbb/concurrent_queue.cpp:47:8: warning: type ‘struct micro_queue’ violates the C++ One Definition Rule [-Wodr]
   47 | struct micro_queue {
      |        ^
../../src/old/concurrent_queue_v2.cpp:40:8: note: a different type is defined in another translation unit
   40 | struct micro_queue {
      |        ^
../../src/tbb/concurrent_queue.cpp:52:19: note: the first difference of corresponding definitions is field ‘head_page’
   52 |     atomic<page*> head_page;
      |                   ^
../../src/old/concurrent_queue_v2.cpp:44:19: note: a field of same name but different type is defined in another translation unit
   44 |     atomic<page*> head_page;
      |                   ^
../../include/tbb/internal/../atomic.h:481:29: note: type name ‘tbb::atomic<tbb::internal::concurrent_queue_base_v3::page*>’ should match type name ‘tbb::atomic<tbb::internal::concurrent_queue_base::page*>’
  481 | template<typename T> struct atomic<T*>: internal::atomic_impl_with_arithmetic<T*,ptrdiff_t,T> {
      |                             ^
../../include/tbb/atomic.h:481:29: note: the incompatible type is defined here
  481 | template<typename T> struct atomic<T*>: internal::atomic_impl_with_arithmetic<T*,ptrdiff_t,T> {
      |                             ^
../../src/tbb/concurrent_queue.cpp:580:7: warning: type ‘struct concurrent_queue_iterator_rep’ violates the C++ One Definition Rule [-Wodr]
  580 | class concurrent_queue_iterator_rep: no_assign {
      |       ^
../../src/old/concurrent_queue_v2.cpp:292:8: note: a different type is defined in another translation unit
  292 | class  concurrent_queue_iterator_rep: no_assign {
      |        ^
../../src/tbb/concurrent_queue.cpp:583:34: note: the first difference of corresponding definitions is field ‘my_queue’
  583 |     const concurrent_queue_base& my_queue;
      |                                  ^
../../src/old/concurrent_queue_v2.cpp:296:34: note: a field of same name but different type is defined in another translation unit
  296 |     const concurrent_queue_base& my_queue;
      |                                  ^
../../src/tbb/concurrent_queue.cpp:580:7: note: type name ‘tbb::internal::concurrent_queue_base_v3’ should match type name ‘tbb::internal::concurrent_queue_base’
  580 | class concurrent_queue_iterator_rep: no_assign {
      |       ^
../../src/tbb/concurrent_queue.cpp:112:7: warning: type ‘struct concurrent_queue_rep’ violates the C++ One Definition Rule [-Wodr]
  112 | class concurrent_queue_rep {
      |       ^
../../src/old/concurrent_queue_v2.cpp:96:7: note: a different type is defined in another translation unit
   96 | class concurrent_queue_rep {
      |       ^
../../src/tbb/concurrent_queue.cpp:130:24: note: the first difference of corresponding definitions is field ‘items_avail’
  130 |     concurrent_monitor items_avail;
      |                        ^
../../src/old/concurrent_queue_v2.cpp:116:10: note: a field with different name is defined in another translation unit
  116 |     char pad1[NFS_MaxLineSize-sizeof(atomic<ticket>)];
../../src/tbbmalloc/proxy.cpp:300:7: warning: ‘void* __libc_valloc(size_t)’ specifies less restrictive attributes than its target ‘void* valloc(size_t)’: ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  300 | void *__libc_valloc(size_t size) __attribute__ ((alias ("valloc")));
      |       ^~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:231:14: note: ‘void* __libc_valloc(size_t)’ target declared here
  231 | void *PREFIX(valloc)(ZONE_ARG size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:166:22: note: in definition of macro ‘PREFIX’
  166 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:299:7: warning: ‘void* __libc_pvalloc(size_t)’ specifies less restrictive attributes than its target ‘void* pvalloc(size_t)’: ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  299 | void *__libc_pvalloc(size_t size) __attribute__ ((alias ("pvalloc")));
      |       ^~~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:261:7: note: ‘void* __libc_pvalloc(size_t)’ target declared here
  261 | void *pvalloc(size_t size) __THROW
      |       ^~~~~~~
../../src/tbbmalloc/proxy.cpp:298:7: warning: ‘void* __libc_memalign(size_t, size_t)’ specifies less restrictive attributes than its target ‘void* memalign(size_t, size_t)’: ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  298 | void *__libc_memalign(size_t alignment, size_t size) __attribute__ ((alias ("memalign")));
      |       ^~~~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:225:14: note: ‘void* __libc_memalign(size_t, size_t)’ target declared here
  225 | void *PREFIX(memalign)(ZONE_ARG size_t alignment, size_t size) __THROW
      |              ^~~~~~~~
../../src/tbbmalloc/proxy.cpp:166:22: note: in definition of macro ‘PREFIX’
  166 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:297:7: warning: ‘void* __libc_calloc(size_t, size_t)’ specifies less restrictive attributes than its target ‘void* calloc(size_t, size_t)’: ‘alloc_size’, ‘leaf’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  297 | void *__libc_calloc(size_t num, size_t size) __attribute__ ((alias ("calloc")));
      |       ^~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:205:14: note: ‘void* __libc_calloc(size_t, size_t)’ target declared here
  205 | void *PREFIX(calloc)(ZONE_ARG size_t num, size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:166:22: note: in definition of macro ‘PREFIX’
  166 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:296:7: warning: ‘void* __libc_malloc(size_t)’ specifies less restrictive attributes than its target ‘void* malloc(size_t)’: ‘alloc_size’, ‘leaf’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  296 | void *__libc_malloc(size_t size) __attribute__ ((alias ("malloc")));
      |       ^~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:200:14: note: ‘void* __libc_malloc(size_t)’ target declared here
  200 | void *PREFIX(malloc)(ZONE_ARG size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:166:22: note: in definition of macro ‘PREFIX’
  166 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:149:18: warning: ‘void* __TBB_malloc_proxy(size_t)’ specifies less restrictive attributes than its target ‘void* malloc(size_t)’: ‘alloc_size’, ‘leaf’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  149 | extern "C" void *__TBB_malloc_proxy(size_t) __attribute__ ((alias ("malloc")));
      |                  ^~~~~~~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:200:14: note: ‘void* __TBB_malloc_proxy(size_t)’ target declared here
  200 | void *PREFIX(malloc)(ZONE_ARG size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:166:22: note: in definition of macro ‘PREFIX’
  166 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:300:7: warning: ‘void* __libc_valloc(size_t)’ specifies less restrictive attributes than its target ‘void* valloc(size_t)’: ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  300 | void *__libc_valloc(size_t size) __attribute__ ((alias ("valloc")));
      |       ^~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:231:14: note: ‘void* __libc_valloc(size_t)’ target declared here
  231 | void *PREFIX(valloc)(ZONE_ARG size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:166:22: note: in definition of macro ‘PREFIX’
  166 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:299:7: warning: ‘void* __libc_pvalloc(size_t)’ specifies less restrictive attributes than its target ‘void* pvalloc(size_t)’: ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  299 | void *__libc_pvalloc(size_t size) __attribute__ ((alias ("pvalloc")));
      |       ^~~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:261:7: note: ‘void* __libc_pvalloc(size_t)’ target declared here
  261 | void *pvalloc(size_t size) __THROW
      |       ^~~~~~~
../../src/tbbmalloc/proxy.cpp:298:7: warning: ‘void* __libc_memalign(size_t, size_t)’ specifies less restrictive attributes than its target ‘void* memalign(size_t, size_t)’: ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  298 | void *__libc_memalign(size_t alignment, size_t size) __attribute__ ((alias ("memalign")));
      |       ^~~~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:225:14: note: ‘void* __libc_memalign(size_t, size_t)’ target declared here
  225 | void *PREFIX(memalign)(ZONE_ARG size_t alignment, size_t size) __THROW
      |              ^~~~~~~~
../../src/tbbmalloc/proxy.cpp:166:22: note: in definition of macro ‘PREFIX’
  166 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:297:7: warning: ‘void* __libc_calloc(size_t, size_t)’ specifies less restrictive attributes than its target ‘void* calloc(size_t, size_t)’: ‘alloc_size’, ‘leaf’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  297 | void *__libc_calloc(size_t num, size_t size) __attribute__ ((alias ("calloc")));
      |       ^~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:205:14: note: ‘void* __libc_calloc(size_t, size_t)’ target declared here
  205 | void *PREFIX(calloc)(ZONE_ARG size_t num, size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:166:22: note: in definition of macro ‘PREFIX’
  166 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:296:7: warning: ‘void* __libc_malloc(size_t)’ specifies less restrictive attributes than its target ‘void* malloc(size_t)’: ‘alloc_size’, ‘leaf’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  296 | void *__libc_malloc(size_t size) __attribute__ ((alias ("malloc")));
      |       ^~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:200:14: note: ‘void* __libc_malloc(size_t)’ target declared here
  200 | void *PREFIX(malloc)(ZONE_ARG size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:166:22: note: in definition of macro ‘PREFIX’
  166 | #define PREFIX(name) name
      |                      ^~~~
../../src/tbbmalloc/proxy.cpp:149:18: warning: ‘void* __TBB_malloc_proxy(size_t)’ specifies less restrictive attributes than its target ‘void* malloc(size_t)’: ‘alloc_size’, ‘leaf’, ‘malloc’, ‘nothrow’ [-Wmissing-attributes]
  149 | extern "C" void *__TBB_malloc_proxy(size_t) __attribute__ ((alias ("malloc")));
      |                  ^~~~~~~~~~~~~~~~~~
../../src/tbbmalloc/proxy.cpp:200:14: note: ‘void* __TBB_malloc_proxy(size_t)’ target declared here
  200 | void *PREFIX(malloc)(ZONE_ARG size_t size) __THROW
      |              ^~~~~~
../../src/tbbmalloc/proxy.cpp:166:22: note: in definition of macro ‘PREFIX’
  166 | #define PREFIX(name) name
      |                      ^~~~

**Comment by ms178** [comment]
The GCC folks told me that they need a testcase. Could someone give me a hint which open source project still relies on 32 bit TBB? I just know of two commercial games and of some open source projects which use the 64 bit binaries.

**Comment by ms178** [comment]
The issue is not reproducable with gcc version 10.0.0 20190704 (experimental) (SUSE Linux) anymore (finally!), hence I am closing this.
