### ISSUE TITLE
2019u7: test_malloc_compliance fails spuriously

### ISSUE THREAD

**Issue by Lastique** [intel/tbb#148]
The test_malloc_compliance test fails sometimes with the following message:

```
sh ../../build/test_launcher.sh  -u ./test_malloc_compliance.exe  1:4
Assertion (uintptr_t)lmb + lmb->unalignedSize >= (uintptr_t)object + lmb->objectSize failed on line 1006 of file ../../src/tbbmalloc/backend.cpp
Detailed description: An object must fit to the block.
Aborted (core dumped)
./test_malloc_compliance.exe: exited with error 134
../../build/Makefile.tbbmalloc:231: recipe for target 'malloc_test_no_depends' failed
```

Full build log attached below.

This happens when debug versions of TBB are built and tested. The problem does not reproduce reliably, it might be related to the number of CPU cores available or CPU load by other processes. I'm building on a 4 core/8 thread CPU with about 50% load from other processes. GCC 8.3 on Kubuntu 19.04.

[tbb_fail.log](https://github.com/intel/tbb/files/3247896/tbb_fail.log)

**Comment by Lastique** [comment]
This did not happen with TBB 2019 Update 5.

**Comment by nik-ponomarev** [comment]
@Lastique thanks for reporting the problem. I could reproduce it on my machine. We will fix this in one of the next releases.

**Comment by tbbdev** [comment]
Fixed in [TBB 2019 U8](https://github.com/intel/tbb/blob/2019_U8/CHANGES).

**Comment by Lastique** [comment]
Thanks.
