### ISSUE TITLE
Not sure how to compile for MSVC 2015

### ISSUE THREAD

**Issue by ASmoliak** [intel/tbb#152]
Hello, recently I've been trying to learn on how to write HPC applications, and many folks have suggested trying out Thread Building Blocks, now I'm pretty sure this is not a place to ask something like this but I have no idea how to compile the library for MSVC 2015, more specifically I need both 32-bit and 64-bit libraries as well as them being statically linked to the CRT.

Going through the build docs, when looking for compilers there is no mention of MSVC being used to compile _(I assume I need to compile with MSVC in order to target MSVC)_

As a person who is woefully ignorant of build systems I would really appreciate some help :)

**Comment by ASmoliak** [comment]
I've installed GnuMake, and after downloading the source package, attempted to run cmake whilst located on the top-level directory, this is what I got:
![image](https://user-images.githubusercontent.com/26040470/59148245-ddfc8580-8a0e-11e9-8acc-9ef0d48de114.png)

**Comment by ntfshard** [comment]
Hello

You should run it in the compiler's command prompt. In the start menu find Visual studio folder and click "x64 Native Tools Command Prompt for VS 2015" for example.

I just want to ask a question: why do really need such linkage configuration. Why official binaries doesn't fit for your purpose?

**Comment by ASmoliak** [comment]
> I just want to ask a question: why do really need such linkage configuration. Why official binaries doesn't fit for your purpose?

There's a bug within a certain build of windows server 2012 R2 that won't allow you to install the visual studio 2015 CRT, the solution is a windows update deployed by Microsoft years ago, but the client refuses to update the system duo to fears of their service going down for too long, the solution is to statically link the CRT.
The reason for 32-bit and 64-bit libraries is also duo to backwards compatibility.

I would like to use TBB to improve the project, but without statically linking, I won't be able to update the release on that certain machine.

**Comment by ASmoliak** [comment]
Your advice has worked friend!
After compilation, the results are located within two folders:
* _windows_intel64_cl_vc14_release_
* _windows_intel64_cl_vc14_debug_

Within, there's a bunch of `.obj` `.dll` and `.pdb` files, but what catches my eye are the `tbb.lib` `tbbmalloc.lib` and `tbbmalloc_proxy.lib` files, in order to use TBB, do I need to link these files and also include the headers in my visual studio projects?

**Comment by ntfshard** [comment]
AFAIS for linking TBB binary with statically linked runtime you should add to make command 'runtime=vc_mt' [see](https://www.threadingbuildingblocks.org/docs/help/reference/appendices/known_issues/windows_os.html)

e.g. `make runtime=vc_mt`

**Comment by ASmoliak** [comment]
It all works! Thanks so much!

**Comment by zengletian1491** [comment]
> Your advice has worked friend!
> After compilation, the results are located within two folders:
> 
> * _windows_intel64_cl_vc14_release_
> * _windows_intel64_cl_vc14_debug_
> 
> Within, there's a bunch of `.obj` `.dll` and `.pdb` files, but what catches my eye are the `tbb.lib` `tbbmalloc.lib` and `tbbmalloc_proxy.lib` files, in order to use TBB, do I need to link these files and also include the headers in my visual studio projects?

> Your advice has worked friend!
> After compilation, the results are located within two folders:
> 
> * _windows_intel64_cl_vc14_release_
> * _windows_intel64_cl_vc14_debug_
> 
> Within, there's a bunch of `.obj` `.dll` and `.pdb` files, but what catches my eye are the `tbb.lib` `tbbmalloc.lib` and `tbbmalloc_proxy.lib` files, in order to use TBB, do I need to link these files and also include the headers in my visual studio projects?

Hello, I'm new to Thread Building Blocks. I type "make" in x64 Native Tools Command Prompt for VS 2017, and the folder "windows_intel64_c1_vc14.1_release" generates. I would like to know what commands can generate the folder "windows_intel64_c1_vc14.1_debug". Thank you.
