### ISSUE TITLE
Official website redirects to shady websites

### ISSUE THREAD

**Issue by Omegastick** [intel/tbb#167]
Not sure if this is the best place to report this, but http://threadingbuildingblocks.org/ is currently redirecting to some shady advertising websites.

I've tried with a few different devices and I'm getting the same result on all of them, so I don't think it's just me.

It was working fine on Friday.

**Comment by Omegastick** [comment]
Seems to be fixed now.

**Comment by phprus** [comment]
NO! Not fixed!
Only first access to http://threadingbuildingblocks.org/ redirect to advertising websites.

Redirect is active now!

**Comment by Omegastick** [comment]
Oh okay, I'll reopen this then.

**Comment by tbbdev** [comment]
Thank you for the issue reporting! We're working on it.

**Comment by zmajeed** [comment]
Here's the redirect for HTTP without www URL in Chrome: http://threadingbuildingblocks.org/

![image](https://user-images.githubusercontent.com/6625550/60804776-4c3a8200-a14c-11e9-9b48-ed54626d3927.png)

This is HTTPS and www: https://www.threadingbuildingblocks.org/

![image](https://user-images.githubusercontent.com/6625550/60805278-9f610480-a14d-11e9-8e28-b0693b6cbe0c.png)

This is HTTPS without www: https://threadingbuildingblocks.org/ 

![image](https://user-images.githubusercontent.com/6625550/60804872-8d329680-a14c-11e9-831e-591014f3c18d.png)

I actually encountered this intermittently on 5 July - now happens every time

It's particularly annoying when following the TBB link on the GCC 9 page announcing support for parallel algorithms: https://www.gnu.org/software/gcc/gcc-9/changes.html

**Comment by bjornpiltz** [comment]
Now Chrome identifies the Windows releases as malware and doesn't let me download them.

**Comment by zmajeed** [comment]
While the site is being fixed how about serving a simple static HTML page with a message about the site being hacked and provide links to the github page. Otherwise users with older browsers are being placed at risk. Also search engines will start to blacklist the site.

**Comment by tbbdev** [comment]
The issue has been resolved.
