### ISSUE TITLE
[cmake] TBBGet.cmake stopped working after package renaming

### ISSUE THREAD

**Issue by anton-malakhov** [intel/tbb#209]
As packages were renamed, regexp in the [line]( https://github.com/intel/tbb/blob/tbb_2020/cmake/TBBGet.cmake#L201) becomes incorrect:
```
string(REGEX REPLACE ".*(https.*oss_${tbb_lib_archive_suffix}).*" "\\1" tbb_bin_url "${tbb_release_info}")
```
Beause it looks for "oss_" which is absent now: https://api.github.com/repos/01org/tbb/releases/latest

**Comment by ivankochin** [comment]
Hi, Anton
Thanks for reporting!
Fix for the issue will be published as part of one of the future releases.
For now, as a workaround, you may just remove the `oss_` prefix from the regular expression.

**Comment by tbbdev** [comment]
Fixed in [TBB 2020 Update 1](https://github.com/intel/tbb/blob/v2020.1/CHANGES#L19).
