### ISSUE TITLE
Can't use official Intel TBB cmake setup for integration into PyTorch

### ISSUE THREAD

**Issue by cpuhrsch** [intel/tbb#62]
Hello all,

We've been successfully using tbb for PyTorch for a while now. It's a great library! However, in order to get it to work we [wrote our own cmake setup](https://github.com/pytorch/pytorch/tree/fd3048708931d47fca3b559a9c1bea86073282e6/aten/src/ATen/cpu/tbb) (largely based on wjakob's [great repository](https://github.com/wjakob/tbb)).

However, this is hard to maintain. I'd like to use the official Intel cmake setup for PyTorch as it is becoming a more and more essential library for our project.

I wrote [a PR](https://github.com/pytorch/pytorch/pull/7972) for this, however I see many failures, mostly with the following signature:

```
23:33:44 -- Building Intel TBB: /usr/bin/make -j4 tbb_build_prefix=tbb_cmake_build_subdir tbb_build_dir=/var/lib/jenkins/workspace/build/tbb_cmake_build compiler=gcc
23:33:47 -- Building is unsuccessful (2): /var/lib/jenkins/workspace/third_party/tbb/./build/Makefile.tbb:32: CONFIG: cfg=debug arch=intel64 compiler=gcc target=linux runtime=cc4.8_libc2.19_kernel4.4.0
23:33:47 /var/lib/jenkins/workspace/third_party/tbb/./build/Makefile.tbb:32: CONFIG: cfg=release arch=intel64 compiler=gcc target=linux runtime=cc4.8_libc2.19_kernel4.4.0
23:33:47 cc: error: backend.o: No such file or directory
23:33:47 cc: error: large_objects.o: No such file or directory
23:33:47 cc: error: backref.o: No such file or directory
23:33:47 cc: error: tbbmalloc.o: No such file or directory
23:33:47 cc: error: frontend.o: No such file or directory
23:33:47 make[1]: *** [libtbbmalloc_debug.so.2] Error 1
23:33:47 make: *** [tbbmalloc] Error 2
```

I'd like to kindly request some help in setting this up or at least an occasional review.

**Comment by nik-ponomarev** [comment]
Hi @cpuhrsch,
you should better use official [FindTBB.cmake](https://github.com/01org/tbb/tree/tbb_2018/cmake) module for this purpose.

**Comment by AlexVeprev** [comment]
@cpuhrsch, seems sources were not built for some reason, maybe there are problems with paths or with permissions. Anyway I'm trying to reproduce it locally for debug. Have you tried it?

**Comment by AlexVeprev** [comment]
I've tried to reproduce the issue using this [Dockerfile](https://github.com/cpuhrsch/pytorch/blob/master/docker/caffe2/ubuntu-16.04-cpu-all-options/Dockerfile).

It looks working, finished with 0 return code:
```
> cmake .. -DBUILD_BINARY=ON -DUSE_OBSERVERS=ON -DUSE_ZSTD=ON -DCMAKE_INSTALL_PREFIX=/usr/local/caffe2 -DPYTHON_EXECUTABLE=/usr/bin/python2 -DUSE_REDIS=ON -DONNX_NAMESPACE=ONNX_NAMESPACE_FOR_C2_CI
...
-- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/tmp/pytorch/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
-- The BLAS backend of choice:Eigen
-- Building Intel TBB: /usr/bin/make -j4 tbb_build_prefix=tbb_cmake_build_subdir tbb_build_dir=/tmp/pytorch/build/tbb_cmake_build compiler=gcc
-- Brace yourself, we are building NNPACK
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.12")
...
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/pytorch/build
```
I'll continue investigation.

**Comment by cpuhrsch** [comment]
Thank you for looking into this @AlexVeprev! Resolving this will make us feel a lot more comfortable in widely adopting this great library.

I've had tried various things previously, but ultimately wrote our current cmake setup. I gave it another shot since the library had been updated recently, so I'll also look into this again more closely. For now I tried to faithfully use the [source package setup described in the README](https://github.com/01org/tbb/tree/tbb_2018/cmake#source-package-integration).

**Comment by AlexVeprev** [comment]
@cpuhrsch, thank you! There are two ways of TBB integration via CMake: binary and source. If you want source integration you implemented it properly as I see.

From the logs I can conclude TBB CMake script works as expected, but the problem appears during execution of internal "make" part. I'm still trying to reproduce it locally but without success... Do you have a suggestion how to do it? Specific Dockerfile?
Another option is to add some debug modifications into your PR or into a separate PR (temporary, of course) to reproduce it on PyTorch infrastructure. Is it possible? It's going to be a little bit tricky as modifications should be applied for TBBBuild.cmake which is checked out directly from TBB repo, but we can dynamically modify it right before:
```cmake
include("${CMAKE_CURRENT_LIST_DIR}/../third_party/tbb/cmake/TBBBuild.cmake")
```

Just to be clear about debug modifications I'm going to do:

- remove OUTPUT_QUIET from internal call of execute_process in TBBBuild.cmake (seems can't be done without modification of TBBBuild.cmake)
- pass verbose arg to "make" command (can be done using interface of tbb_build)
